tui.Editor.i18n.setLang(['en', 'en_US'], {
    'Markdown': 'Markdown',
    'WYSIWYG': 'WYSIWYG',
    'Headings': 'Headings',
    'Paragraph': 'Paragraph',
    'Bold': 'Bold',
    'Italic': 'Italic',
    'Strike': 'Strike',
    'Code': 'Code',
    'Line': 'Line',
    'Blockquote': 'Blockquote',
    'Unordered list': 'Unordered list',
    'Ordered list': 'Ordered list',
    'Task': 'Task',
    'Insert link': 'Insert link',
    'Insert codeblock': 'Insert codeblock',
    'Insert table': 'Insert table',
    'Insert image': 'Insert image',
    'Heading': 'Heading',
    'Image URL': 'Image URL',
    'Select image file': 'Select image file',
    'Description': 'Description',
    'OK': 'OK',
    'Cancel': 'Cancel',
    'File': 'File',
    'URL': 'URL',
    'Link text': 'Link text',
    'Add row': 'Add row',
    'Add col': 'Add col',
    'Remove row': 'Remove row',
    'Remove col': 'Remove col',
    'Align left': 'Align left',
    'Align center': 'Align center',
    'Align right': 'Align right',
    'Remove table': 'Remove table',
    'Would you like to paste as table?': 'Would you like to paste as table?',
    'Text color': 'Text color',
    'Auto scroll enabled': 'Auto scroll enabled',
    'Auto scroll disabled': 'Auto scroll disabled'
});
