tui.Editor.i18n.setLang('ja_JP', {
    'Markdown': 'マークダウン',
    'WYSIWYG': 'WYSIWYG',
    'Headings': '見出し',
    'Bold': '太字',
    'Italic': '斜体',
    'Strike': 'ストライク',
    'Code': 'コード',
    'Line': 'ライン',
    'Blockquote': 'Blockquote',
    'Unordered list': '順不同リスト',
    'Ordered list': '順序付きリスト',
    'Task': 'タスク',
    'Insert link': 'リンクを挿入します',
    'Insert codeblock': 'コードブロックを挿入',
    'Insert table': 'テーブルの挿入',
    'Insert image': '画像挿入',
    'Heading': '見出し',
    'Image URL': 'イメージURL',
    'Select image file': '選択した画像ファイル',
    'Description': '説明',
    'OK': 'はい',
    'Cancel': 'キャンセル',
    'File': 'ファイル',
    'URL': 'URL',
    'Link text': 'リンクテキスト',
    'Add row': '行を追加します。',
    'Add col': '列を追加',
    'Remove row': '行を削除',
    'Remove col': '列を削除してください',
    'Align left': '整列左',
    'Align center': '中央揃え',
    'Align right': '右揃え',
    'Remove table': 'テーブルを削除してください',
    'Would you like to paste as table?': 'あなたはテーブルとして貼り付けしたいです?'
});
