tui.Editor.i18n.setLang(['ja', 'ja_JP'], {
    'Markdown': 'マークダウン',
    'WYSIWYG': 'WYSIWYG',
    'Headings': '見出し',
    'Bold': '太字',
    'Italic': 'イタリック',
    'Strike': 'ストライク',
    'Code': 'コード',
    'Line': 'ライン',
    'Blockquote': '引用',
    'Unordered list': '番号なしリスト',
    'Ordered list': '順序付きリスト',
    'Task': 'タスク',
    'Insert link': 'リンク挿入',
    'Insert codeblock': 'コードブロック挿入',
    'Insert table': 'テーブル挿入',
    'Insert image': '画像挿入',
    'Heading': '見出し',
    'Image URL': 'イメージURL',
    'Select image file': '画像ファイル選択',
    'Description': 'ディスクリプション ',
    'OK': 'はい',
    'Cancel': 'キャンセル',
    'File': 'ファイル',
    'URL': 'URL',
    'Link text': 'リンクテキスト',
    'Add row': '行追加',
    'Add col': '列追加',
    'Remove row': '行削除',
    'Remove col': '列削除',
    'Align left': '左揃え',
    'Align center': '中央揃え',
    'Align right': '右揃え',
    'Remove table': 'テーブル削除',
    'Would you like to paste as table?': 'テーブルを貼り付けますか?'
});
