tui.Editor.i18n.setLang('ko_KR', {
    'Markdown': '마크다운',
    'WYSIWYG': '위지윅',
    'Headings': '제목크기',
    'Bold': '굵게',
    'Italic': '기울임꼴',
    'Strike': '취소선',
    'Code': '코드',
    'Line': '문단나눔',
    'Blockquote': '인용구',
    'Unordered list': '글머리 기호',
    'Ordered list': '번호 매기기',
    'Task': '체크박스',
    'Insert link': '링크 삽입',
    'Insert codeblock': '코드블럭 삽입',
    'Insert table': '표 삽입',
    'Insert image': '이미지 삽입',
    'Heading': '제목',
    'Image URL': '이미지 주소',
    'Select image file': '이미지 파일을 선택하세요.',
    'Description': '설명',
    'OK': '확인',
    'Cancel': '취소',
    'File': '파일',
    'URL': '주소',
    'Link text': '링크 텍스트',
    'Add row': '행 추가',
    'Add col': '열 추가',
    'Remove row': '행 삭제',
    'Remove col': '열 삭제',
    'Align left': '왼쪽 정렬',
    'Align center': '가운데 정렬',
    'Align right': '오른쪽 정렬',
    'Remove table': '표 삭제',
    'Would you like to paste as table?': '표형태로 붙여 넣겠습니까?'
});
