tui.Editor.i18n.setLang(['nl', 'nl_NL'], {
    'Markdown': 'Markdown',
    'WYSIWYG': 'WYSIWYG',
    'Headings': 'Koppen',
    'Paragraph': 'tekst',
    'Bold': 'Vet',
    'Italic': 'Cursief',
    'Strike': 'Doorhalen',
    'Code': 'Code',
    'Line': 'Regel',
    'Blockquote': 'Citaatblok',
    'Unordered list': 'Opsomming',
    'Ordered list': 'Genummerde opsomming',
    'Task': 'Taak',
    'Insert link': 'Link invoegen',
    'Insert codeblock': 'Codeblok toevoegen',
    'Insert table': 'Tabel invoegen',
    'Insert image': 'Afbeelding invoegen',
    'Heading': 'Kop',
    'Image URL': 'Afbeelding URL',
    'Select image file': 'Selecteer een afbeelding',
    'Description': 'Omschrijving',
    'OK': 'OK',
    'Cancel': 'Annuleren',
    'File': 'Bestand',
    'URL': 'URL',
    'Link text': 'Link tekst',
    'Add row': 'Rij toevoegen',
    'Add col': 'Kolom toevoegen',
    'Remove row': 'Rij verwijderen',
    'Remove col': 'Kolom verwijderen',
    'Align left': 'Links uitlijnen',
    'Align center': 'Centreren',
    'Align right': 'Rechts uitlijnen',
    'Remove table': 'Verwijder tabel',
    'Would you like to paste as table?': 'Wil je dit als tabel plakken?',
    'Text color': 'Tekstkleur',
    'Auto scroll enabled': 'Autoscroll ingeschakeld',
    'Auto scroll disabled': 'Autoscroll uitgeschakeld',
    'Cannot paste values ​​other than a table in the cell selection state':'Kan geen waardes anders dan de tabel in de cell plakken'
});
