tui.Editor.i18n.setLang(['zh', 'zh_CN'], {
    'Markdown': '降价',
    'WYSIWYG': '所见即所得',
    'Headings': '标题',
    'Bold': '大胆',
    'Italic': '斜体',
    'Strike': '罢工',
    'Code': '代码',
    'Line': '行',
    'Blockquote': '大段引用',
    'Unordered list': '无序列表',
    'Ordered list': '有序列表',
    'Task': '任务',
    'Insert link': '插入链接',
    'Insert codeblock': '插入代码块',
    'Insert table': '插入表格',
    'Insert image': '插入图片',
    'Heading': '标题',
    'Image URL': '图片网址',
    'Select image file': '选择映像文件',
    'Description': '说明',
    'OK': '好的',
    'Cancel': '取消',
    'File': '文件',
    'URL': 'URL',
    'Link text': '链接文本',
    'Add row': '添加一行',
    'Add col': '添加山坳',
    'Remove row': '删除行',
    'Remove col': '删除山坳',
    'Align left': '左对齐',
    'Align center': '居中对齐',
    'Align right': '右对齐',
    'Remove table': '删除表',
    'Would you like to paste as table?': '你想粘贴为表?'
});
