name: Editor Check Types
on: pull_request
jobs: 
  check-types:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '15.x'
      - name: Install
        run: |
          npm ci
      - name: check types
        run: |
          npm run test:types:all