name: detect runtime error

on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  makeUrl:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: create config variable
        run: |
          node ../apps/editor/scripts/createConfigVariable.js
      - name: set global error variable
        run: |
          echo ::set-env name=ERROR_VARIABLE::$(head -n 1 ./errorVariable.txt)
      - name: set url
        run: |
          echo ::set-env name=URLS::$(head -n 1 ./url.txt)
      - name: detect runtime error
        uses: nhn/toast-ui.detect-runtime-error-actions@master
        with:
          global-error-log-variable: ${{ env.ERROR_VARIABLE }}
          urls: ${{ env.URLS }}
        env:
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
