name: Editor Unit, Integration Test
on: pull_request
jobs: 
  test:
    name: Unit, Integration Test
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: |
          npm install
      - name: build toastmark
        run: |
          npm run build toastmark
      - name: toastmark unit, integration test
        run: |
          npm run test toastmark
      - name: editor unit, integration test
        run: |
          npm run test editor