name: Editor Unit, Integration Test
on: pull_request
jobs: 
  test:
    name: Unit, Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '15.x'
      - name: Install
        run: |
          npm ci
      - name: build toastmark
        run: |
          npm run build toastmark
      - name: toastmark unit, integration test
        run: |
          npm run test:ci toastmark
      - name: editor unit, integration test
        run: |
          npm run test:ci editor